site_name: Cracktrader Documentation
site_description: A modern cryptocurrency trading framework that bridges CCXT and Backtrader
site_url: https://your-domain.com/cracktrader-docs  # Update with your VPS domain

repo_name: cracktrader
edit_uri: ""  # Disable edit links for private repo




theme:
  name: material
  palette:
    # Palette toggle for dark mode (default)
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - .
        - ..
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
      - Quickstart: getting_started/quickstart.md
      - Installation: getting_started/installation.md
      - First Strategy: getting_started/first_strategy.md
      - Configuration: getting_started/configuration.md
  - How-to:
      - Strategy Cookbook: strategy_guide.md
      - Web API: WEB_API.md
      - Backtrader Compatibility: integrations/backtrader_compat.md
  - Concepts:
      - Architecture: core_concepts/architecture.md
      - Strategies: core_concepts/strategies.md
      - Feeds: core_concepts/feeds.md
      - Brokers: core_concepts/brokers.md
      - Exchanges: core_concepts/exchanges.md
      - Caching: core_concepts/caching.md
  - Reference:
      - Web API Reference: reference/web_api.md
      - Configuration Reference: reference/configuration.md
  - Development:
      - Performance:
          - Overview: performance/overview.md
          - Caching Guide: performance/caching_guide.md
          - Large Datasets: performance/large_datasets.md
          - Benchmarking: performance/benchmarking.md
          - Optimization Roadmap: performance/optimization_roadmap.md
      - Testing & Quality:
          - Strategy Analysis: testing/strategy_analysis.md
          - Fixtures & Sample Strategy: testing/fixture_strategy.md
          - Mocking Policy: testing/mocking_policy.md
          - Test Coverage Status: testing/test_coverage.md
          - Known Gaps: testing/known_gaps.md
      - Contributing:
          - Overview: development/README.md
          - Workflow: development/workflow.md
          - Quick Reference: development/quick-reference.md
          - Testing Guidelines: development/testing_guidelines.md
          - Publishing: development/publishing.md
  - Project (internal):
      - Documentation plan: internal/DOCUMENTATION_PLAN.md
      - Documentation status: internal/DOCUMENTATION_STATUS.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            merge_init_into_class: true
            show_submodules: true

extra_css:
  - assets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LachlanBridges/cracktrader
      name: GitHub Repository
